<?php if (count($flash) > 0): ?>

    <ul>
        <?php foreach ($flash as $messages): ?>
            <?php foreach ($messages as $message): ?>
                <li><?= $message ?></li>
            <?php endforeach ?>
        <?php endforeach ?>
    </ul>
<?php endif ?>
<?php if (isset($currentUser)): ?>
    <form action="/" method="post">
        <label>
            Sign out
            <input type="hidden" name="_METHOD" value="DELETE">
            <input type="submit" value="Sign Out">
        </label>
    </form>
<?php else: ?>
    <div>
        <h3>You are not authenticated!</h3>
    </div>
    <div>
        <a href="/session">Sign in</a>
    </div>
    <div>
        <a href="/create">Sign up</a>
    </div>
<?php endif ?>
