development:
  adapter: sqlite
  database: database/database.sqlite
  pool: 5
  timeout: 5000

test:
  adapter: sqlite
  database: database/database.sqlite
  pool: 5
  timeout: 5000

production:
  adapter: sqlite
  database: database/database.sqlite
  pool: 5
  timeout: 5000